TARGET = xspress4

PLATFORM = x86_64
CROSS_COMPILE = 

CC = $(CROSS_COMPILE)gcc
CFLAGS = -g -Wall -fmessage-length=0 -std=gnu99

INCLUDES =  ../include/xsp4_driver.h ../../include/xspress3.h

OBJ_DIR= objs.$(PLATFORM)
BIN_DIR = ../../../../bin.$(PLATFORM)

OBJS = $(OBJ_DIR)/xspress4_lib_dummy.o

INCLUDE_DIRS =	-I../include -I../../include

CFLAGS += $(INCLUDE_DIRS)
CFLAGS += -I../../../../libs/include
LIB_DIR = ../../../../libs/libs.linux.$(PLATFORM)/lib
LIB = $(OBJ_DIR)/lib$(TARGET).a

$(LIB): $(OBJS)
	rm -f $@
	$(CROSS_COMPILE)ar rc $@ $(OBJS)
	$(CROSS_COMPILE)ranlib $@

all: $(LIB)

install: $(LIB)
	(cd ../include; chmod 644 *.h; cp *.h ../../../../libs/include)
	chmod 644 $(LIB)
	cp $(LIB) ../../../../libs/libs.linux.$(PLATFORM)/lib

clean:
	rm -f $(OBJS) $(LIB)

#------------------------------------------------------------------------------
#--  rule: ./*.c
#------------------------------------------------------------------------------
$(OBJ_DIR)/%.o: %.c $(INCLUDES)
	@echo "Compiling $< ..."
	$(CC) $(CFLAGS) -c $< -o $@
	